fos_rest:
  body_listener: true
  format_listener:
    rules:
      - { priorities: ['json'], fallback_format: json, prefer_extension: false }
  view:
    view_response_listener: true
    formats:
      json: true
    templating_formats:
      json: true
    failed_validation: HTTP_BAD_REQUEST
  routing_loader:
    default_format: json
    include_format: false
  exception:
    enabled: true
