version: '3.4'

services:
  #    db:
  #        container_name: db-todo
  #        image: postgres
  #        restart: always
  #        environment:
  #            - POSTGRES_USER=root
  #            - POSTGRES_PASSWORD=root
  #            - POSTGRES_DB=todo_dev
  #        ports:
  #            - "5432:5432"
  #        volumes:
  #            - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    networks:
      - todo
  php:
    build:
      context: ./provision/php
    working_dir: /var/www/todo
    environment:
      - DEFAULT_TIMEZONE=UTC
      - PHP_IDE_CONFIG=serverName=PHPSTORM
    volumes:
      - .:/var/www/todo
      - ./provision/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - todo

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/todo:cached
      - ./provision/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - todo
#volumes:
#    postgres_data:

networks:
  todo:
    external:
      name: todo
